services:
  hyperbeam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

    volumes:
      - ./config.flat:/app/config.flat:ro
      - ./mywallet.json:/app/mywallet.json:ro
      - ./hyperbeam_data:/app/data

    # Either single-line command:
    command: ["/app/bin/hb", "foreground"]

    tty: true
