services:
  hyperbeam:
    build: .
    ports:
      - "10000:10000"

    environment:
      HB_PORT: "10000"

    volumes:
      - ./config.flat:/app/config.flat:ro
      - ./mywallet.json:/app/mywallet.json:ro
      - ./hyperbeam_data:/app/data

      # Either single-line command:
    command: ["/app/bin/hb", "foreground"]

    tty: true
