version: "3.8"

services:
  hyperbeam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"

    volumes:
      - ./config.flat:/app/config.flat:ro
      - ./mywallet.json:/app/mywallet.json:ro
      - ./hyperbeam_data:/app/hyperbeam_data

    # Either single-line command:
    command: >
      rebar3 shell --eval "hb:start_mainnet(#{port => 9001, key_location => '/app/mywallet.json', store => {hb_store_fs, #{prefix => '/app/hyperbeam_data'}}})."

    tty: true
