services:
  hyperbeam:
    build: .
    ports:
      - "10000:10000"

    environment:
      HB_PORT: "10000"
      HB_KEY_LOCATION: "/app/mywallet.json"

    volumes:
      - ./config.flat:/app/config.flat:ro
      - ./mywallet.json:/app/mywallet.json:ro
      - ./hyperbeam_data:/app/data
    command:
      [
        "/app/bin/hb",
        "foreground",
        "-eval",
        'hb:start_mainnet(#{ port => 10000, key_location => "/app/mywallet.json" }).',
      ]
